import type { DirectoryModel } from "@/lib/model-directory";

/**
 * Public model directory — facts match Neuralwatt portal cards (context, $/M
 * input, cached/output split, caps, effort). Cursor exchange: $1.15 ↔ 1M tokens.
 */
export const DIRECTORY_MODELS: DirectoryModel[] = [
  {
    id: "kimi-k3",
    name: "Kimi K3",
    identifier: "kimi-k3",
    provider: "MoonshotAI",
    description:
      "Moonshot AI Kimi K3 — multimodal 2.8T MoE, 1M context.",
    capabilities: ["reasoning", "vision", "tools", "json", "flex"],
    rates: {
      inputPerMillion: 3.0,
      cachedInputPerMillion: 0.3,
      outputPerMillion: 15.0,
    },
    contextTokens: 1_048_576,
    effort: "max (default) / high / low / none",
    status: "Available",
    available: true,
    cta: "try_now",
    popularity: 11,
  },
  {
    id: "kimi-k3-fast",
    name: "Kimi K3 Fast",
    identifier: "kimi-k3-fast",
    provider: "MoonshotAI",
    description:
      "Moonshot AI Kimi K3 with thinking mode disabled for instant, lower-latency responses.",
    capabilities: ["vision", "tools", "json", "flex"],
    rates: {
      inputPerMillion: 3.0,
      cachedInputPerMillion: 0.3,
      outputPerMillion: 15.0,
    },
    contextTokens: 1_048_576,
    effort: "none (default)",
    status: "Available",
    available: true,
    cta: "try_now",
    popularity: 10,
  },
  {
    id: "glm-5-3",
    name: "GLM 5.3",
    identifier: "glm-5.3",
    provider: "ZhipuAI",
    description:
      "ZhipuAI GLM 5.3 with always-on reasoning and 1M context window.",
    capabilities: ["reasoning", "tools", "flex"],
    rates: {
      inputPerMillion: 1.45,
      cachedInputPerMillion: 0.14,
      outputPerMillion: 4.5,
    },
    contextTokens: 1_048_576,
    effort: "max (default) / high / low · always on",
    status: "Available",
    available: true,
    cta: "try_now",
    popularity: 9,
  },
  {
    id: "glm-5-3-flash",
    name: "GLM-5.3 Flash",
    identifier: "glm-5.3-flash",
    provider: "ZhipuAI",
    description:
      "ZhipuAI GLM-5.3 Flash with vision, tools, flex, and always-on reasoning.",
    capabilities: ["reasoning", "vision", "tools", "flex"],
    rates: {
      inputPerMillion: 0.15,
      cachedInputPerMillion: 0.03,
      outputPerMillion: 0.5,
    },
    contextTokens: 1_048_576,
    effort: "max (default) / high / low · always on",
    status: "Available",
    available: true,
    cta: "try_now",
    popularity: 8,
  },
  {
    id: "deepseek-v4-flash",
    name: "DeepSeek V4 Flash",
    identifier: "deepseek-v4-flash",
    provider: "DeepSeek",
    description:
      "Fast DeepSeek route with 1M context, tools, JSON, and flex effort.",
    capabilities: ["reasoning", "tools", "json", "flex"],
    rates: {
      inputPerMillion: 0.14,
      cachedInputPerMillion: 0.03,
      outputPerMillion: 0.28,
    },
    contextTokens: 1_048_576,
    effort: "max / high / none (default)",
    status: "Available",
    available: true,
    cta: "try_now",
    popularity: 7,
  },
  {
    id: "deepseek-v4-1-flash",
    name: "DeepSeek V4.1 Flash",
    identifier: "deepseek-v4.1-flash",
    provider: "DeepSeek",
    description:
      "DeepSeek V4.1 Flash — MoE with tool calling and adjustable reasoning effort. 1M-token native context.",
    capabilities: ["reasoning", "vision", "tools", "json"],
    rates: {
      inputPerMillion: 0.15,
      cachedInputPerMillion: 0.02,
      outputPerMillion: 0.6,
    },
    contextTokens: 1_048_576,
    status: "Preview",
    available: true,
    badges: ["Preview"],
    cta: "request_access",
    popularity: 6,
  },
  {
    id: "deepseek-v4-pro",
    name: "DeepSeek V4-Pro",
    identifier: "deepseek-v4-pro",
    provider: "DeepSeek",
    description:
      "Higher-quality DeepSeek Pro route; request access while in preview.",
    capabilities: ["reasoning", "tools", "json"],
    rates: {
      inputPerMillion: 1.0,
      cachedInputPerMillion: 0.1,
      outputPerMillion: 3.0,
    },
    contextTokens: 1_048_576,
    effort: "max / high / low (default) / none",
    status: "Preview",
    available: true,
    badges: ["Preview"],
    cta: "request_access",
    popularity: 5,
  },
  {
    id: "gemma-4-31b",
    name: "Gemma 4 31B",
    identifier: "gemma-4-31b",
    provider: "nvidia",
    description:
      "Google Gemma 4 31B — multimodal (text + vision) with tool calling and 262K context.",
    capabilities: ["reasoning", "vision", "tools", "json"],
    rates: {
      inputPerMillion: 0.14,
      cachedInputPerMillion: 0.01,
      outputPerMillion: 0.42,
    },
    contextTokens: 262_144,
    effort: "max / none (default)",
    status: "Available",
    available: true,
    cta: "try_now",
    popularity: 4,
  },
  {
    id: "glm-5-2",
    name: "GLM-5.2",
    identifier: "glm-5.2",
    provider: "ZhipuAI",
    description:
      "ZhipuAI GLM-5.2 for coding agents, tool calls, and chat completions.",
    capabilities: ["reasoning", "tools", "flex"],
    rates: {
      inputPerMillion: 1.45,
      cachedInputPerMillion: 0.14,
      outputPerMillion: 4.5,
    },
    contextTokens: 1_048_576,
    effort: "max (default) / high / none",
    status: "Available",
    available: true,
    cta: "try_now",
    popularity: 3,
  },
  {
    id: "qwen-3-8-27b",
    name: "Qwen 3.8 27B",
    identifier: "qwen-3.8-27b",
    provider: "Qwen",
    description:
      "Qwen3.8-27B — dense 27B VL model with MTP speculative decoding, native 262K context.",
    capabilities: ["reasoning", "vision", "tools", "json"],
    rates: {
      inputPerMillion: 0.45,
      cachedInputPerMillion: 0.25,
      outputPerMillion: 3.2,
    },
    contextTokens: 262_144,
    effort: "xhigh (default) / medium / low / none",
    status: "Preview",
    available: true,
    badges: ["Preview"],
    cta: "request_access",
    popularity: 2,
  },
  {
    id: "qwen3-embedding-8b",
    name: "Qwen3 Embedding 8B",
    identifier: "qwen3-embedding-8b",
    provider: "Qwen",
    description:
      "Qwen3-Embedding-8B — dense 8B text embedding model, 4096-dim. First embedding model on the platform.",
    capabilities: ["embedding"],
    rates: {
      inputPerMillion: 0.01,
      cachedInputPerMillion: 0.0,
      outputPerMillion: 0.0,
    },
    contextTokens: 8_192,
    status: "Preview",
    available: true,
    badges: ["Preview"],
    cta: "request_access",
    popularity: 1,
  },
];
